# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python compilacion

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.14", "3.13", "3.12"]

    steps:
    - name: Traer codigo
      uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest
        python -m pip install ruff
        python -m pip install pyright
        python -m pip install uv
        uv pip install --system --no-cache-dir -e .
        uv sync

    - name: Validar codigo con ruff
      run: |
        ruff check .
    - name: Ejecutar pruebas
      run: |
        pytest tests.py


    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ghcr.io/${{ github.repository }} # Replace with your image name
        tags: |
          type=semver,pattern={{version}} # Uses the release version as a tag

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: . # Path to your Dockerfile context
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
    
    # - name: Descargar imagen docker
    #   uses: actions/download-artifact@v4
    #   with:
    #     name: python-app-ci-image
    #     path: image.tar
    
    # - name: Cargar imagen docker
    #   run: docker load -i image.tar
    
    # - name: Ejecutar contenedor docker
    #   run: docker run -p 8000:8000 python-app-ci-image
